language: cpp
arch:
    - amd64
    - ppc64le
compiler:
    - gcc
    - clang

before_install:
    - if [ $TRAVIS_CPU_ARCH = amd64 ]; then
            ./admin/travis-install-deps.sh ;
      fi
env:
    - ARCH=amd64 AS_ROOT=no
    - ARCH=amd64 AS_ROOT=yes
    - ARCH=i386 AS_ROOT=no
    - ARCH=ppc64le AS_ROOT=no
matrix:
    exclude:
        - compiler: clang
          env: ARCH=i386 AS_ROOT=no
        - arch: ppc64le
          env: ARCH=amd64 AS_ROOT=no
        - arch: ppc64le
          env: ARCH=amd64 AS_ROOT=yes
        - arch: amd64 
          env: ARCH=ppc64le AS_ROOT=no
               
script:
    - ./admin/travis-build.sh

notifications:
    email:
        - atf-log@googlegroups.com
